before_install: git clone -b travis $(git config --get remote.origin.url) target/travis
script: mvn deploy --settings target/travis/settings.xml
branches:
  except:
  - travis
env:
  global:
  - secure: KnLWdJ/Mugs1HA/4z1xcfiLLoEnRFxpxUkbbhMCjZIrqeV7ZhtIxDUkWv9VuGRBvEtj9C/t4qKN/WPLcDQNXmfABpWSUHVPyQ/3GYCXK3FkuICbg/XmPO9OWLx7bw5poRRQIbge2typIFyActeUVrDuCsk8E661GmZKEWTuIfPQ=
  - secure: khIj8HjcW3EhUEuf7LIZjl6KmBxsZFRVHd6/oi08W4XqZAJc6iFDum5452vwGQYBmvb7WtUFPYTTF+AY/B4YWv5/kFz6pYAhI7fiIY7JyGDfrvs3tkZx40WMjuyOcTBYu0yzWU3TjzCGGxHMEAc3L/ht9+ugip2Iiv88v4/J29M=
